Allow grouping + date ranges to filter the stats.
Charitable/Charitable-Stat-Shortcode pull request #12
Opened 2022-03-04 01:44 UTC by daamsie

Added some extra options for the shortcode. These will output tables with data rather than simple numbers.

2022-03-23 06:21 UTC, ericnicolaas requested changes
A few comments.

2022-03-23 06:21 UTC, ericnicolaas commented on class-charitable-donation-report.php
> +			}
Could we change this to two arguments: `date_before` and `date_after`?

The above only supports a before/after combo, and it will also break if you have a comma in either date, even though `strtotime( 'January 1, 2020' )` is valid. 

Not needing to set a before, for example, would mean you can get all donations since Jan 1 2022, without needing to update the date before or setting it to a date in the future.

2022-03-23 06:21 UTC, ericnicolaas commented on class-charitable-stat-shortcode.php
> +
Same comment as above

2022-03-23 06:21 UTC, ericnicolaas commented on class-charitable-stat-shortcode.php
> +					}
Looks to me like this would only work for grouping donors by campaign, as the report for donations doesn't handle grouping (so you can't get number of donations by campaign). And for campaigns it obviously doesn't make sense. 

I think to make it clearer what's working here, I'd probably break 'donors' into its own switch case (and maybe bundle 'donations' into that if you add support for grouping there too.

2022-03-24 04:28 UTC, daamsie commented on class-charitable-stat-shortcode.php
> +
Done

2022-03-24 04:28 UTC, daamsie commented on class-charitable-stat-shortcode.php
> +					}
Yeah fair point. Fixed that up.

2022-03-24 11:35 UTC, merged